# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchIphone():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchIphone(self):
    self.driver.get("https://www.amazon.com/?ref=rd_www_amazon_ph_en/")
    self.driver.set_window_size(724, 680)
    element = self.driver.find_element(By.ID, "nav-search-submit-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "twotabsearchtextbox").click()
    self.driver.find_element(By.ID, "twotabsearchtextbox").send_keys("iphone")
    self.driver.find_element(By.ID, "twotabsearchtextbox").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Today\'s Deals").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    assert self.driver.title == "Amazon | Deals"
    self.driver.find_element(By.LINK_TEXT, "Coupons").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-cart-icon").click()
  
