
*** Variables ***
# *XPaths

${Create_Request_xpath}  //div[@id='app-root-container']/div/div/div/dew-route-loader/div[2]/eproc-online-store/dew-page-wrapper/div/dew-spotlight/div/div[3]/div/div[2]/div/div/eproc-main-search/div[2]/span[2]

${Add item_Service_xpath}  //*[@id="grid-input"]/div/div[2]/div[2]/dew-btn/button/div/span

${Category_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/eproc-create-guided-item-dialog/form/dew-modal/div[2]/div/div[2]/dew-modal-body/div/dew-row[1]/dew-col[2]/dew-input-container/dew-typeahead/div/div[2]/div/div/div

${Sourcing_status_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/eproc-create-guided-item-dialog/form/dew-modal/div[2]/div/div[2]/dew-modal-body/div/dew-row[4]/dew-col/dew-input-container/div[2]/div[1]/label

${Next_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/eproc-create-guided-item-dialog/form/dew-modal/div[2]/div/div[3]/dew-modal-footer/input

${Supplier_xpath}  

${Supplier_first_xpath}  //*[@id="grid-input"]/div/div[2]/div[1]/div[2]/div[1]/dew-row/dew-col[1]/div/input

${Add_details_xpath}  //*[@id="grid-input"]/div/div[2]/div[2]/dew-btn/button/div/span

${Supplier_address_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/dew-page-wrapper/div/div/dew-page-content/form/div/dew-block/div[1]/div/dew-row[1]/dew-col[1]/dew-row/dew-col[3]/eproc-autocomplete-supplier/eproc-supplier-detail-dialog/dew-modal/div[2]/div/div[2]/dew-modal-body/div/div/div/dew-row[1]/dew-col/dew-input-container/dew-dropdown/div/div/dew-dropdown-trigger/textarea

${Supplier_val}  //*[@id="cdk-overlay-6"]/div[2]/div/div[1]/div/a

${Done_Btn_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/dew-page-wrapper/div/div/dew-page-content/form/div/dew-block/div[1]/div/dew-row[1]/dew-col[1]/dew-row/dew-col[3]/eproc-autocomplete-supplier/eproc-supplier-detail-dialog/dew-modal/div[2]/div/div[3]/dew-modal-footer/dew-btn/button/div/span

${Checkout_Btn_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/dew-footer-actions/footer/div/div/dew-btn[3]/button/div/span

${eForm_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/eproc-create-guided-item-dialog/form/dew-modal/div[2]/div/div[2]/dew-modal-body/div/dew-row[1]/dew-col[4]/dew-input-container/div/label/div[1]

${eForm_value1_xpath}  //*[@id="app-root-container"]/div/div/div/dew-route-loader/div[2]/eproc-guided-procurement/eproc-create-guided-item-dialog/form/dew-modal/div[2]/div/div[2]/dew-modal-body/div/dew-row[1]/dew-col[4]/dew-input-container/dew-select/dew-dropdown/div/div/dew-dropdown-trigger/p

${eForm_value2_xpath}  //*[@id="cdk-overlay-16"]/div[2]/div/div[2]